### ISSUE TITLE
How accurate is this decompiled source code to the original

### ISSUE THREAD

**Issue by balenol** [rmon-vfer/yandereSimulatorSource#14]
@rmon-vfer Is there any accuracy rate from your decompilation technique with the original source code? How close is it? If there's a lot of if else statement inside of yandev's code, was it because of the inaccuracy of the decompilation technique or his own inability to write decent code?

**Comment by SoulRepo** [comment]
It's the original code. Download the build and use dnspy. There are a lot of if else statements. His code sucks.

**Comment by EBTheHero** [comment]
Well first there can't be any comments because the compilers drops all of them.

**Comment by Col-E** [comment]
Its likely that control flow is largely the same. You're not going to see a `switch` statement transformed into a million `if` branches.  Maybe you'll see something like `if (myBool()) {a} else {b}` transform into `if (!myBool()) {b} else {a}`

Now, there are cases where you will see things _(opaque predicates)_ like `if (!false)` instead of `if (true)`. Any good compiler should transform `if(true)` into a single jump instruction. therefore I'm inclined to believe this is a decompiler artifact. Consider it as a failure to inline certain behavior.
```c
PUSH 0
IFEQ -> LABEL
// some code here, default fallthrough case
LABEL: // destination if pushed value == 0
```
This behavior is logically equivalent to:
```c
GOTO -> LABEL
// some code here, unused/skipped
LABEL: // destination of goto
```
